### PR TITLE
feature/hashcons hashcons and primes implementation

### PR DESCRIPTION
**Pull request by amir734jj**

### CODE REVIEW

**Review by boyland — CHANGES_REQUESTED** [review]
All in all, this looks pretty clean and neat.  
The sieve function is not incremental but that's fine.
But I have a few comments that should be addressed.

primes.c: 69: This if statement is redundant I think -- not wrong, just wastes time
hashcons.c: 176: You try to use unary minus to make the result be non-negative, but:
   the spec doesn't say that the result will be non-negative;
   the unary minus will fail occasionally (-MININT == MININT);
   hash_string doesn't seem to prevent negative values.
   I would recommend getting rid of the attempt.
hashcons.c:32 This line doesn't work if hash is negative.  Must fix.
hashcons.c:44 Ditto

**Review by boyland — COMMENTED** [review]
You still are *trying* to keep hash values positive, but that is not possible.  Stop doing that.
You still are not handling a negative hash value correctly.
You got rid of the (good) conditional setting od step_size; that's OK, but it also still doesn't handle negative hash values correctly.

**Comment by amir734jj** [comment]
Hi Professor,

Did you meant to use `& 0xfffffff` operation to keep the values positive?

Thank you so much,

**Comment by boyland** [comment]
No.  You should handle hash being negative.  That means after doing the % operation, you have to handle the result being negative.  At *that* point, you can either use unary minus or add the divisor to get a positive number.

**Review by boyland — COMMENTED** [review]
You are still trying to prevent hash values from being negative.  Don't do this.  Handle it instead.

**Review by boyland — COMMENTED** [review]
Line 32 (anding the step_size with 0xfffffff) is wrong.  Please consider what the requirement is for step_size (what are its bounds?).

**Comment by amir734jj** [comment]
Yes. It was very wrong. I am so sorry. I will re-test the code from now on after making any change.

**Review by boyland — COMMENTED** [review]
Better.  And now I take back a previous criticism: go ahead and put the & 0xfffff (better: the appropriate  MAXINT constant) back on line 30 so that line 31 works too.

**Review by boyland — CHANGES_REQUESTED** [review]
Good.  But use standard definition from <limits.h>  I think it's called INT_MAX

**Comment by boyland** [comment]
What does `primes.size || INITIAL_SIZE` mean?

**Comment by amir734jj** [comment]
If `primes.size` is zero, it uses the `INITIAL_SIZE`

**Comment by boyland** [comment]
```
int main() 
{
    int x = 0 || 42;
    printf("0 || 42 = %d\n",x);
}
```
gets output `0 || 42 = 1`

**Comment by boyland** [comment]
How about `primes.size + INITIAL_SIZE ?`

**Review by boyland — COMMENTED** [review]
has_cons_get should check the capacity *after* adding something rather than *before* seeing if anything is there.

**Review by boyland — APPROVED** [review]
Looks good!

**Pull request merged**
