### PR TITLE
Ensure that actuals exist in the signature

### PR DESCRIPTION
**Pull request by amir734jj**
**Description**
Ensure actuals in the signature for both generating and non-generating modules.

```
module GEN[T :: BASIC] extends LIST[T] -- missing actuals for BASIC
module EXT[T :: BASIC] extends T       -- missing actuals for BASIC
```

**Implementation**
- For generating module it gets caught in `do_bind`
- For non-generating module, it gets caught in `add_ext_sig` and again in `do_bind`

**Validation**
Used regression testing against `simple-binding-1,2,3` and cool and it did not break any existing feature.

### CODE REVIEW

**Comment by amir734jj** [comment]
Fixed the missing `break` in `add_ext_sig`

**Comment by amir734jj** [comment]
@boyland 
Hi Professor. I moved the code down just before the default arm of the `switch` so the behavior of the function stays exactly the same.

**Comment by boyland** [comment]
Please add a comment "/* FALLTHROUGH */" to indicate sig_use intentionally falls through to default.  Otherwise, ready to go.

**Review by boyland — APPROVED** [review]
Good.

**Pull request merged**
