### PR TITLE
Hashcons data structure

### PR DESCRIPTION
**Pull request by amir734jj**
Added hash cons data structure. Note that:

- `stdlib.h` provides `malloc`
- `string.h` provides `memset`

### CODE REVIEW

**Comment by amir734jj** [comment]
@boyland 
Hi Professor. I did some major improvements to the `hashcons`. The major improvement is removed the unnecessary second loop.

**Comment by amir734jj** [comment]
Hi Professor. I corrected the code. Thank you so much for the feedback.

**Comment by boyland** [comment]
primes looking better.

**Comment by boyland** [comment]
in the makefile hashcons.o should depend on prime.h. Otherwise looks great.

**Comment by amir734jj** [comment]
Closing this MR. I will include hashcons in the canonical signature branch

**Pull request closed without merging**
