### PR TITLE
Canonical type logic (no code generation)

### PR DESCRIPTION
**Pull request by amir734jj**

### CODE REVIEW

**Review by boyland — COMMENTED** [review]
It seems you are using hash_cons for sets: but (1) the semantics seem wrong: they depend on the order being the same.  or do you sort them (by memory order) somewhere? (2) shouldn't this be a separate ADT because it makes sense to have a hashcons'set ADT that does sets of pointers (and only pointers to avoid having to handle equality).

**Comment by amir734jj** [comment]
Yes Professor. The logic to sort canonical types is in `union_canonical_signature_set` / `canonical-signature.c`. So we always make sure the set of canonical signatures is sorted, and the hashconsed canonical types will be unique.

**Review by boyland — CHANGES_REQUESTED** [review]
Please use the new hash cons set stuff (once that is approved).

**Review by boyland — APPROVED** [review]
Looks good.

**Pull request merged**
